Use Study_Material --Database Name
GO

-- Authors 
Create Table Authors(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	FullName NVARCHAR(255) NOT NULL,
	Country NVARCHAR(30) NULL,
	DOB DATETIME2 NULL,
	Created DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	CreatedBy NVARCHAR(255) NOT NULL,
	Updated DATETIME2(3) NULL,
	UpdatedBy NVARCHAR(255) NULL,

	CONSTRAINT PK_Author PRIMARY KEY CLUSTERED (Id)
)
GO

-- Books 
Create Table Books(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	Title NVARCHAR(255) NOT NULL,
	ISBN VARCHAR(20) UNIQUE NOT NULL,
	PublicationYear SMALLINT NOT NULL,
	Genre NVARCHAR(20) NOT NULL,
	Created DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	CreatedBy NVARCHAR(255) NOT NULL,
	Updated DATETIME2(3) NULL,
	UpdatedBy NVARCHAR(255) NULL,

	CONSTRAINT PK_Book PRIMARY KEY CLUSTERED (Id),
	CONSTRAINT CK_Book_PublicationYear CHECK(PublicationYear BETWEEN 1000 AND 9999),
)
GO

-- Author and Book mapping
Create Table AuthorBookMapping(
	BookId UNIQUEIDENTIFIER NOT NULL,
	AuthorId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT PK_AuthorBookMapping PRIMARY KEY CLUSTERED (BookId, AuthorId),
	CONSTRAINT FK_AuthorBookMapping_Book FOREIGN KEY(BookId) REFERENCES Books(Id),
	CONSTRAINT FK_AuthorBookMapping_Author FOREIGN KEY(AuthorId) REFERENCES Authors(Id)
)
GO

-- Borrowers 
Create Table Users(
	Id UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	FullName NVARCHAR(255) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	PhoneNumber NVARCHAR(20) NOT NULL,
	Created DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	CreatedBy NVARCHAR(255) NOT NULL,
	Updated DATETIME2(3) NULL,
	UpdatedBy NVARCHAR(255) NULL,

	CONSTRAINT PK_User PRIMARY KEY CLUSTERED (Id)
)
GO

-- BorrowerRecords 
Create Table BorrowerRecords(
	BookId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	BorrowDate DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
	ReturnDate DATETIME2(3) NULL,
	Status NVARCHAR(10) NOT NULL,

	CONSTRAINT PK_BorrowerRecords PRIMARY KEY CLUSTERED (BookId, UserId),
	CONSTRAINT FK_BorrowerRecords_Book FOREIGN KEY(BookId) REFERENCES Books(Id),
	CONSTRAINT FK_BorrowerRecords_User FOREIGN KEY(UserId) REFERENCES Users(Id)
)